version: "3.8"

services:
  app-backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=appbackend.settings
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: