name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: dev-database
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker-compose -f docker-compose-dev.yml build

    - name: Start services
      run: docker-compose -f docker-compose-dev.yml up -d

    - name: Wait for database to be ready
      run: docker-compose -f docker-compose-dev.yml exec -T db sh -c 'while ! pg_isready -q; do sleep 1; done'

    - name: Run tests
      run: docker-compose -f docker-compose-dev.yml exec web python manage.py test