name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django pylint pylint-django 
        pip install dj_database_url python-decouple
        pip install djangorestframework
    - name: Set Django settings module
      run: |
        export DJANGO_SETTINGS_MODULE=appbackend.settings
    - name: Analysing the code with pylint
      run: |
        pylint --load-plugins pylint_django --django-settings=appbackend.settings --ignore=tasks/migrations $(git ls-files '*.py')